// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using news.feed.Config.EntityFramework;

#nullable disable

namespace news.feed.Migrations
{
    [DbContext(typeof(NewsFeedContext))]
    [Migration("20260523210141_AddIndexByBodyIdForAttachments")]
    partial class AddIndexByBodyIdForAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("news.feed.models.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NewsBodyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NewsBodyId" }, "IX_attachments_NewsBodyId");

                    b.ToTable("news_attachment", (string)null);
                });

            modelBuilder.Entity("news.feed.models.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BodyId")
                        .HasColumnType("uuid");

                    b.Property<long>("CreationTime")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long>("UpdateTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Program" }, "IX_news_Program");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("news.feed.models.Models.NewsBody", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("news_body", (string)null);
                });

            modelBuilder.Entity("news.feed.models.Models.Program", b =>
                {
                    b.Property<string>("Alias")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Alias");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("news_program", (string)null);
                });

            modelBuilder.Entity("news.feed.models.Models.Attachment", b =>
                {
                    b.HasOne("news.feed.models.Models.NewsBody", null)
                        .WithMany("Attachments")
                        .HasForeignKey("NewsBodyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("news.feed.models.Models.News", b =>
                {
                    b.HasOne("news.feed.models.Models.Program", null)
                        .WithMany("News")
                        .HasForeignKey("Program")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("news.feed.models.Models.NewsBody", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("news.feed.models.Models.Program", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
