// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using news.feed.Config.EntityFramework;

#nullable disable

namespace news.feed.Migrations
{
    [DbContext(typeof(NewsFeedContext))]
    [Migration("20260410185006_RemoveIdGeneration")]
    partial class RemoveIdGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("news.feed.models.Models.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BodyId")
                        .HasColumnType("char(36)");

                    b.Property<long>("CreationTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<long>("UpdateTime")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Program");

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("news.feed.models.Models.NewsBody", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("news_body", (string)null);
                });

            modelBuilder.Entity("news.feed.models.Models.Program", b =>
                {
                    b.Property<string>("Alias")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Alias");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.ToTable("news_program", (string)null);
                });

            modelBuilder.Entity("news.feed.models.Models.News", b =>
                {
                    b.HasOne("news.feed.models.Models.Program", null)
                        .WithMany("News")
                        .HasForeignKey("Program")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("news.feed.models.Models.Program", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
